name: Update Profile SVGs

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dateutil requests
          
      - name: Update SVGs
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python today.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dark_mode.svg light_mode.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update SVGs"
          git push
